import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import MenuComponent from "./component/menu/menu";
import Link from "next/link";
import CheckComponent from "./project_slide";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "ShinJiYun_PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex flex-col">
        <Link href="/">
          <div className="text-6xl text-center font-extrabold">
            PORTFOLIO
          </div>
        </Link>
        <div className="flex flex-grow w-full h-full">
          <div className="w-1/12 absolute z-10">
            <MenuComponent />
          </div>
          <div className="flex-grow ml-7 mt-2 z-0 flex justify-center items-center flex-col">
            <div className="bg-red-200 flex items-center justify-center w-11/12 h-5/6 scrollable-content overflow-y-scroll">
              {children}
            </div>
            <div className="w-full">
              <CheckComponent/>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
