import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import MenuComponent from "./component/menu/menu";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "ShinJiYun_PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex flex-col">
        <div className="text-6xl text-center h-1/10">
          PORTFOLIO
        </div>
        <div className="flex flex-grow relative w-full">
          <div className="w-2/10 absolute z-10">
            <MenuComponent/>
          </div>
          <div className="flex-grow absolute ml-7 mt-2 h-full w-full z-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
