import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import MenuComponent from "./component/menu/menu";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "ShinJiYun_PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex flex-col">
        <div className="text-6xl text-center h-1/10">
          PORTFOLIO
        </div>
        <div className="flex flex-grow w-full">
          <div className="w-1/4 absolute z-10">
            <MenuComponent/>
          </div>
          <div className="flex-grow ml-7 mt-2 z-0">
            <div className="bg-red-200 w-full h-full flex items-center justify-center">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
